--- 
- hosts: all
  become: yes 
  gather_facts: yes
  tasks: 
  - name: i want to install webserver on ubuntu nodes 
    apt: 
       name: "{{mywebserverforubuntu}}" 
       state: present 
    when: ansible_os_family =="Debian"  

  - name: i want to start webserver on ubuntu nodes 
    service:
       name: "{{mywebserverforubuntu}}" 
       state: started
    when: ansible_os_family =="Debian" 

  - name: i want to install webserver on RedHat nodes 
    ansible.builtin.dnf:
       name: "{{mywebserverforredhat}}"
       state: present
    when: ansible_os_family =="RedHat" 
  
  - name: i want to start webserver on RedHat nodes 
    service:
       name: "{{mywebserverforredhat}}"
       state: started
    when: ansible_os_family =="RedHat" 
  